#项目配置信息
app:
  env: dev
  run_mode: debug
  gao_de_key: 04cfb5ac488dd032b40cb590e7659ae7

server:
  http: 8080
  websocket: 8081
  tcp: 8082

log:
  path: "./temp"

mysql:
  host: 59.110.137.58
  port: 3307
  username: root
  password: xin1223
  dbname: test
  parameters: "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"

redis:
  host: 59.110.137.58
  port: 6379
  auth: xin1223
  database: 0

jwt:
  secret: 836c3fea9bba4e04d51bd0fbcc5
  expires_time: 3600
  buffer_time: 3600

email:
  host: smtp.163.com
  smtp: smtp.163.com:25
  addr: tich0425@163.com
  name: test
  password: FLBUHLEVTPDMLUWY
  expires: 10