#项目配置信息
app:
  env: dev
  run_mode: debug

server:
  http: 8080
  websocket: 8081
  tcp: 8082

log:
  path: "./temp"

mysql:
  host: 59.110.137.58
  port: 3307
  username: root
  password: xin1223
  dbname: test
  parameters: "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"
